#!/bin/bash

function ee {
    echo $1
    eval $1
}


if [ -n "$1" ]
then
  POD_STRING="$1"
  printf -v ESCAPED "%q" "$1"
  ee "echo \"$1\" >> Podfile"
  ee "pod install && git add . && git commit -m \"Add $ESCAPED\""
else
  echo "Usage: add_and_install_pod [pod string]"
fi
