#!/bin/bash

if [ -n "$1" ]
then
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
git stash
git checkout develop
git stash apply
git commit  -a -m "$1"
git checkout $CURRENT_BRANCH
else
echo "Usage: commit_in_develop [commit message]"
fi
