#!/bin/bash

function ee {
    echo $1
    eval $1
}

if [ -n "$1" ]
then
  BRANCH_TO="$1"
  CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
  ee 'git checkout $BRANCH_TO'
  ee 'git merge --no-ff $CURRENT_BRANCH'
  ee 'git checkout $CURRENT_BRANCH'
  ee 'git rebase $BRANCH_TO'
else
  echo "Usage: merge_rebase_to [branch]"
fi
