#!/bin/bash

# Get the current SSID
SSID=$(networksetup -getairportnetwork en0 | awk -F': ' '{print $2}')

# Use the security command to get the password
PASSWORD=$(security find-generic-password -D "AirPort network password" -wa "$SSID")

# Get the security type
SECURITY=$(\
  /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I \
  | awk -F': ' '/^ *Security/ {print $2}' \
)

# Adjust the security type for the QR code
case "$SECURITY" in
  "WPA2 Personal")
    SECURITY="WPA"
    ;;
  "WEP")
    SECURITY="WEP"
    ;;
  "None")
    SECURITY="nopass"
    ;;
  *)
    SECURITY="WPA"
    ;;
esac

echo "SSID: $SSID"
echo "Password: $PASSWORD"
echo "Security: $SECURITY"

# Generate QR code for WiFi access
qrencode -t ANSIUTF8 "WIFI:T:$SECURITY;S:$SSID;P:$PASSWORD;;"
