#!/bin/bash

# Get the current SSID
SSID=$(networksetup -getairportnetwork en0 | awk -F': ' '{print $2}')

# Use the security command to get the password
PASSWORD=$(security find-generic-password -D "AirPort network password" -wa "$SSID")

echo "SSID: $SSID"
echo "Password: $PASSWORD"

# Generate QR code for WiFi access (WPA/WPA2)
qrencode -t ANSIUTF8 "WIFI:T:WPA;S:$SSID;P:$PASSWORD;;"
